definitions:
  outputForms.Counts:
    properties:
      page:
        type: integer
      per_page:
        type: integer
      total:
        type: integer
      total_page:
        type: integer
    type: object
  outputForms.State:
    properties:
      code:
        type: integer
      counts:
        $ref: '#/definitions/outputForms.Counts'
      data:
        type: any
      detail:
        type: string
      message:
        type: string
      status:
        type: boolean
    type: object
info:
  contact: {}
  description: OHLC is large amount of historical OHLC price data in CSV files format,
    which now needs to be centralized and digitized.
  termsOfService: http://swagger.io/terms/
  title: Historical OHCL Price Data docs
  version: "1.0"
paths:
  /data:
    get:
      consumes:
      - application/json
      description: get
      parameters:
      - default: 1
        description: page
        in: query
        name: page
        required: true
        type: integer
      - default: 5
        description: per page
        in: query
        name: per_page
        required: true
        type: integer
      - description: symbol
        in: query
        name: symbol
        type: string
      - description: open
        in: query
        name: open
        type: string
      - description: unix
        in: query
        name: unix
        type: string
      - description: high
        in: query
        name: high
        type: string
      - description: low
        in: query
        name: low
        type: string
      - description: close
        in: query
        name: close
        type: string
      - description: created at
        in: query
        name: created_at
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/outputForms.State'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/outputForms.State'
      summary: returns all data.
      tags:
      - data
    post:
      consumes:
      - application/json
      description: post data
      parameters:
      - description: resource files
        in: formData
        name: files
        required: true
        type: file
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/outputForms.State'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/outputForms.State'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/outputForms.State'
      summary: post gives a files from formData and insert records quickly.
      tags:
      - data
swagger: "2.0"
